name: GitActions_Node_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
    
  build-node:
    runs-on: ${{ matrix.node-version }}
    permissions:
      checks: writes
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    #container: node:16
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: node --version
    - run: npm --version
    - uses: actions/checkout@v4.1.5
    - run: npm install
    - run: npm test
    - run: node app.js
